# Array Creation
### 1 Using Existing Data
### 2 Using Ones and Zeros
### 3 Using Numerical Ranges

Revision of Lists

In [2]:
abc=[4,5,7]

In [4]:
print(abc)

[4, 5, 7]


In [5]:
print(type(abc))

<class 'list'>


## Using Existing Data List / Tuples

In [18]:
import numpy

### Using List

In [11]:
a=numpy.array([2,3,5])

In [12]:
print(a)

[2 3 5]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


### Slicing on Numpy 

In [43]:
a

array([2, 3, 5])

In [44]:
a[0]

2

In [45]:
a[1:3]

array([3, 5])

### Using Tuples 

In [14]:
var=("hi",12,13.5,(3+2j),bool)

In [15]:
var

('hi', 12, 13.5, (3+2j), bool)

In [16]:
print(type(var))

<class 'tuple'>


In [21]:
var=numpy.array(var)

In [22]:
print(var)

['hi' 12 13.5 (3+2j) <class 'bool'>]


### Numpy Operations using List 

In [23]:
a=numpy.array([2,3,5])

In [33]:
a+2

array([4, 5, 7])

In [34]:
a*2

array([ 4,  6, 10])

In [35]:
import numpy as np

In [36]:
b=np.array([3,5,6])

In [37]:
import numpy as np
np.array(b)

array([3, 5, 6])

In [38]:
a

array([2, 3, 5])

In [39]:
print(type(a))

<class 'numpy.ndarray'>


In [40]:
c=np.array(b)*np.array(a)

In [41]:
c

array([ 6, 15, 30])

### Matrix Operation 

In [66]:
import numpy as np
p=np.array([[2,5,6],[1,2,3],[0,4,2]])
p

array([[2, 5, 6],
       [1, 2, 3],
       [0, 4, 2]])

In [67]:
q=np.array([[2,5,6],[1,2,4],[2,2,3]])

print(q)

[[2 5 6]
 [1 2 4]
 [2 2 3]]


In [68]:
p+q

array([[ 4, 10, 12],
       [ 2,  4,  7],
       [ 2,  6,  5]])

In [69]:
p-q

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [-2,  2, -1]])

In [70]:
p*q

array([[ 4, 25, 36],
       [ 1,  4, 12],
       [ 0,  8,  6]])

In [71]:
a=p.dot(q)
print(a)


[[21 32 50]
 [10 15 23]
 [ 8 12 22]]


In [73]:
np.transpose(p)

array([[2, 1, 0],
       [5, 2, 4],
       [6, 3, 2]])

### 2D array

In [30]:
np_a=np.array([[2,3,4],[4,9,16]])

In [31]:
np_a

array([[ 2,  3,  4],
       [ 4,  9, 16]])

In [32]:
np_a.shape

(2, 3)

In [33]:
np_a[0][2]

4

In [34]:
np_a[0:1]

array([[2, 3, 4]])

# Numpy Using Ones and Zeros

In [4]:
np.zeros(shape=(4,3),dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Using Range Function

In [6]:
d=np.arange(start=0,stop=20)

In [7]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.linspace(start=0,stop=20,num=5)

array([ 0.,  5., 10., 15., 20.])

In [9]:
x = np.arange(start=0,stop=20)
x.shape

(20,)

In [10]:
y = x.reshape(5,4)

In [11]:
# 20 elements in x
z = x.reshape(6,3)

ValueError: cannot reshape array of size 20 into shape (6,3)

In [12]:
z = np.arange(10,25).reshape(3,5)
z

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
np.arange(10,25).reshape(5,3) # end is excluded

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

### Numpy random 

In [14]:
#random.random
np.random.seed(99)
np.random.random((5,4)) # 0 to 1

array([[0.67227856, 0.4880784 , 0.82549517, 0.03144639],
       [0.80804996, 0.56561742, 0.2976225 , 0.04669572],
       [0.9906274 , 0.00682573, 0.76979303, 0.7467671 ],
       [0.37743894, 0.49414745, 0.92894839, 0.39545404],
       [0.9739563 , 0.52441472, 0.09361309, 0.81330841]])

In [15]:
np.random.seed(9999)
np.random.randint(low=0,high=50,size=(4,5))

array([[22, 49, 47, 45, 28],
       [37, 25, 38, 24, 16],
       [12, 40, 33, 46,  5],
       [33, 32, 15, 38, 36]])

### Statistical Functions

### Numpy Operation on N Dimentional Array  

In [17]:
x=np.arange(start=0,stop=20)

In [19]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
print(type(x))

<class 'numpy.ndarray'>


In [18]:
np.mean(x)

9.5

In [21]:
np.sum(x)

190

In [22]:
np.median(x)

9.5

In [23]:
np.max(x)

19

In [24]:
np.min(x)

0

### Numpy Operation on N Dimentional Array  

In [26]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
p.min()

1

In [29]:
np.min(p)

1

In [28]:
p.max()

9

In [30]:
np.max(p)

9

### Slicing 

In [32]:
p[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [33]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
p[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
p[:1]

array([[1, 2, 3]])

In [45]:
np.min(p)

1

In [46]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.max(p)

9

In [50]:
np.max(p,axis=0)  # column-wise

array([7, 8, 9])

In [51]:
np.min(p,axis=1) # row-wise

array([1, 4, 7])

In [52]:
np.transpose(p)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
np.sum(p,axis=0)

array([12, 15, 18])

In [54]:
np.sum(p,axis=1)

array([ 6, 15, 24])

In [55]:
np.sum(p)

45